### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by pemensik** [k13132/flowping#2]
Only we mentions desired license. At least for our Fedora packages [we require](https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text) source code to contain full copy of licensing terms. It does not matter if it is LICENSE or COPYING file or any other, but the license should be contained in repository.

GPLv3 in plain text format can be fetched from: https://www.gnu.org/licenses/gpl-3.0.txt

**Comment by vondrous** [comment]
Thank you for your note. Licence copy was just added to src directory.
